entity_patterns = [    
    {"label": "PERSON", "pattern": "Harry Potter"},
    {"label": "PERSON", "pattern": "Harry"},
    {"label": "PERSON", "pattern": "Potter"},
    {"label": "PERSON", "pattern": "Hermione Granger"},
    {"label": "PERSON", "pattern": "Hermione"},
    {"label": "PERSON", "pattern": "Granger"},
    {"label": "PERSON", "pattern": "Ron Weasley"},
    {"label": "PERSON", "pattern": "Ron"},
    {"label": "PERSON", "pattern": "Weasley"},
    {"label": "PERSON", "pattern": "Albus Dumbledore"},
    {"label": "PERSON", "pattern": "Albus"},
    {"label": "PERSON", "pattern": "Dumbledore"},
    {"label": "PERSON", "pattern": "Severus Snape"},
    {"label": "PERSON", "pattern": "Severus"},
    {"label": "PERSON", "pattern": "Snape"},
    {"label": "PERSON", "pattern": "Rubeus Hagrid"},
    {"label": "PERSON", "pattern": "Rubeus"},
    {"label": "PERSON", "pattern": "Hagrid"},
    {"label": "PERSON", "pattern": "Sirius Black"},
    {"label": "PERSON", "pattern": "Sirius"},
    {"label": "PERSON", "pattern": "Black"},
    {"label": "PERSON", "pattern": "Remus Lupin"},
    {"label": "PERSON", "pattern": "Remus"},
    {"label": "PERSON", "pattern": "Lupin"},
    {"label": "PERSON", "pattern": "Ginny Weasley"},
    {"label": "PERSON", "pattern": "Ginny"},
    {"label": "PERSON", "pattern": "Neville Longbottom"},
    {"label": "PERSON", "pattern": "Neville"},
    {"label": "PERSON", "pattern": "Longbottom"},
    {"label": "PERSON", "pattern": "Draco Malfoy"},
    {"label": "PERSON", "pattern": "Draco"},
    {"label": "PERSON", "pattern": "Malfoy"},
    {"label": "PERSON", "pattern": "Lucius Malfoy"},
    {"label": "PERSON", "pattern": "Lucius"},
    {"label": "PERSON", "pattern": "Bellatrix Lestrange"},
    {"label": "PERSON", "pattern": "Bellatrix"},
    {"label": "PERSON", "pattern": "Lestrange"},
    {"label": "ORG", "pattern": "Hogwarts"},    
    {"label": "ORG", "pattern": "Ministry of Magic"},    
    {"label": "ORG", "pattern": "Death Eaters"},    
    {"label": "ORG", "pattern": "Order of the Phoenix"},    
    {"label": "ORG", "pattern": "Dumbledore's Army"},    
    {"label": "ORG", "pattern": "Gringotts"},    
    {"label": "ORG", "pattern": "Daily Prophet"},    
    {"label": "ORG", "pattern": "Knights of Walpurgis"},    
    {"label": "ORG", "pattern": "Slug Club"},    
    {"label": "ORG", "pattern": "Inquisitorial Squad"},    
    {"label": "ORG", "pattern": "Sacred Twenty-Eight"},    
    {"label": "ORG", "pattern": "Wizengamot"},    
    {"label": "ORG", "pattern": "St. Mungo's Hospital"},    
    {"label": "ORG", "pattern": "The Quibbler"},    
    {"label": "ORG", "pattern": "International Confederation of Wizards"},    
    {"label": "ORG", "pattern": "Magical Congress of the United States of America"},    
    {"label": "ORG", "pattern": "Gobstones Club"},    
    {"label": "ORG", "pattern": "British Ministry of Magic"},    
    {"label": "ORG", "pattern": "Department of Mysteries"},    
    {"label": "ORG", "pattern": "Department of Magical Law Enforcement"},    
    {"label": "ORG", "pattern": "Department of International Magical Cooperation"},    
    {"label": "ORG", "pattern": "Department of Magical Accidents and Catastrophes"},    
    {"label": "ORG", "pattern": "Department of Magical Transportation"},    
    {"label": "ORG", "pattern": "Department of Magical Games and Sports"},    
    {"label": "ORG", "pattern": "Department of Magical Education"},    
    {"label": "ORG", "pattern": "Department of Magical Maintenance"},    
    {"label": "ORG", "pattern": "Ministry of Magic Maintenance Department"},    
    {"label": "ORG", "pattern": "Office of the Minister for Magic"},    
    {"label": "ORG", "pattern": "Wizengamot Administration Services"},    
    {"label": "ORG", "pattern": "Improper Use of Magic Office"},    
    {"label": "ORG", "pattern": "Muggle-Born Registration Commission"},    
    {"label": "ORG", "pattern": "Snape's Army"},    
    {"label": "ORG", "pattern": "Slug Club"},    
    {"label": "ORG", "pattern": "Dueling Club"},    
    {"label": "ORG", "pattern": "Magical Law Enforcement Patrol"},    
    {"label": "ORG", "pattern": "Department for the Regulation and Control of Magical Creatures"}
]