patterns = [
    [r'.*I.*to talk.*about (.*)',
     ["Indeed i would like to talk about {0}.",
      "Ok, I'm listening.",
      "How come?",
      "Do you think {0} could have the potential to change something in the muggle world?",
      "Why do you want to talk about {0}?"]],

    [r'I need (.*)',
     ["What is your purpose for needing the {0} spell?",
      "Would casting the {0} spell truly aid you?",
      "Are you positive that the {0} spell is necessary?",
      "Have you considered using alternative magic for {0}?",
      "Perhaps there is a different spell that can achieve the same results as {0}.",
      "It's possible that obtaining {0} is outside the realm of magic."]],

    [r'Why don\'?t you ([^\?]*)\??',
     ["Do you truly believe I'm incapable of performing the {0} spell?",
      "It's possible that I will {0} at some point in the future.",
      "Would you like me to cast the {0} spell right now?",
      "It could be that I have not yet learned the {0} spell.",
      "Have you considered asking me to teach you the {0} spell?",
      "Maybe there are certain circumstances that prevent me from {0}.",
      "It's possible that I choose not to use magic for {0}."]],

    [r'Why can\'?t I ([^\?]*)\??',
     ["Do you think you should be able to {0} with magic?",
      "If you could {0} with magic, what would you do?",
      "I'm not sure, why can't you perform the {0} spell?",
      "Have you tried using magic to {0}?",
      "It might help if you told me what's preventing you from {0}.",
      "Have you tried asking a fellow wizard or witch for assistance with {0}?",
      "Maybe there's a spell or potion that can help with {0}.",
      "It's possible that there are limitations on magic that prevent you from {0}.",
      "Have you considered visiting the Department of Magical Accidents and Catastrophes for help with {0}?"]],

    [r'I can\'?t (.*)',
     ["How do you know you can't {0}?",
      "Have you tried casting a spell or using magic to achieve {0}?",
      "Have you sought guidance from the Ministry of Magic or a wizarding professor?",
      "Have you tried using a spell or potion to help with {0}?",
      "It's said that the impossible is often the untried. Have you tried experimenting with different spells and incantations to achieve {0}?",
      "Sometimes, the solution to a difficult task lies within the heart of a wizard. Have you tried exploring your inner magic for {0}?",
      "Are you sure it's not just a matter of practicing your wandwork or incantations? With enough training, anything is possible, even {0}.",
      "In our world, the impossible is only a matter of perspective. Have you considered seeking guidance from a more experienced wizard or consulting magical books to find a solution for {0}?",
      "Maybe seeking the advice of a wise wizard or witch would help you with {0}."]],

    [r'I am (.*)',
     ["Have you sought me out because you've become {0}?",
      "For how long have you been experiencing the sensation of being {0}?",
      "What emotions are stirred within you now that you are {0}?",
      "Is there a spell or potion that may have caused you to become {0}?",
      "Have you sought guidance from the Ministry of Magic regarding your condition as {0}?",
      "It might be helpful if you told me more about how you came to be {0}.",
      "Have you considered visiting St. Mungo's Hospital for Magical Maladies and Injuries to help understand why you are {0}?"]],

    [r'I\'?m (.*)',
     ["How does being {0} make you feel?",
      "Do you enjoy being {0}?",
      "Why do you tell me you're {0}?",
      "Why do you think you're {0}?",
      "How does being a wizard or witch who is {0} affect your magic?",
      "Do you think your being {0} has any connection to the wizarding world?",
      "Could it be that your {0} state is a result of a spell or curse?",
      "Do you think that your {0} state affects those around you in the wizarding community?"]]
]
